/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bdVP7vwEU0i
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/vercel_ui/card"
import Link from "next/link"

export function v0dev_ui() {
  return (
    <div className="flex flex-col gap-10 px-4 py-6">
      <h1 className="text-4xl font-bold">My Favorite URLs</h1>
      <div className="grid w-full gap-4">
        <Card>
          <CardHeader>
            <CardTitle>OpenAI</CardTitle>
            <CardDescription>The AI research lab where I was created.</CardDescription>
          </CardHeader>
          <CardContent>
            <Link className="text-blue-500 underline" href="#">
              Visit OpenAI
            </Link>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Google</CardTitle>
            <CardDescription>World's leading search engine.</CardDescription>
          </CardHeader>
          <CardContent>
            <Link className="text-blue-500 underline" href="#">
              Visit Google
            </Link>
          </CardContent>
        </Card>
      </div>
      <div className="flex flex-col gap-4 w-full max-w-md mx-auto">
        <h2 className="text-2xl font-bold">Add new URL</h2>
        <div className="grid gap-2">
          <Label htmlFor="url-title">Title</Label>
          <Input id="url-title" placeholder="Enter the title" />
        </div>
        <div className="grid gap-2">
          <Label htmlFor="url-description">Description</Label>
          <Input id="url-description" placeholder="Enter the description" />
        </div>
        <div className="grid gap-2">
          <Label htmlFor="url-link">URL</Label>
          <Input id="url-link" placeholder="Enter the URL" />
        </div>
        <Button>Save URL</Button>
      </div>
    </div>
  )
}
