/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bdVP7vwEU0i
 */
import {CardTitle, CardDescription, CardHeader, CardContent, Card} from "@/components/vercel_ui/Card"
import Link from "next/link"


export function V0dev_ui(category, favoritesBlogData) {
    return (
        <div className="flex flex-col gap-10 px-4 py-6">
            <h1 className="text-4xl font-bold">My Favorite {category}</h1>
            <div className="grid w-full gap-4">
                {favoritesBlogData.linkList.map((d) => (
                    <Card>
                        <CardHeader>
                            <CardTitle>{d.title}</CardTitle>
                            <CardDescription>{d.description}</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <Link className="text-blue-500 underline" href={d.href} target="_blank">
                                {d.visit}
                            </Link>
                        </CardContent>
                    </Card>
                ))}
            </div>
        </div>
    )
}
